services:
  next.js:
    build: #コンテナ1
      context: . #コンテキスト
      dockerfile: ./Dockerfile.next.js
    container_name: next.js #コンテナ名
    working_dir: /ngo #作業ディレクトリを/appに設定
    command: npm run dev -- -p 3100 #ポート3100で起動
    volumes:
      - .:/app
    ports:
      - 3100:3100
    depends_on:
      - db

  db: #コンテナ2
    image: postgres:14 #イメージ名
    container_name: next.js-test-network-db
    # container_name: db #コンテナ名
    restart: always #常に再起動
    # command: --skip-grant-tables --skip-networking #MySQLサーバーは特定のセキュリティ機能を無効
    environment:
      # POSTGRES_ROOT_PASSWORD: tt #rootパスワード
      POSTGRES_USER: tt #ユーザ名
      POSTGRES_PASSWORD: tt #パスワード
      POSTGRES_DB: DB #データベース名
    volumes:
      - ./src/app/DB/:/docker-entrypoint-initdb.d/ #/init.sql #初期化スクリプト
      - db:/var/lib/postgresql/data #データ永続化
    ports:
      - "5432:5432" #ホストのポート5432をコンテナのポート5432にマッピング

networks: #ネットワーク
  default:
    name: next.js-test-network

volumes: #ボリューム
  db:
    driver: local #ボリュームドライバ
