services:
  next.js:
    build: #コンテナ1
      dockerfile: ./Dockerfile.next.js
    container_name: next.js #コンテナ名
    command: npm run dev
    volumes:
      - ./:/page
    ports:
      - 3100:3100

  db: #コンテナ2
    image: postgres:14 #イメージ名
    # container_name: db #コンテナ名
    restart: always #常に再起動
    # command: --skip-grant-tables --skip-networking #MySQLサーバーは特定のセキュリティ機能を無効
    environment:
      MYSQL_ROOT_PASSWORD: tt #rootパスワード
      MYSQL_USER: tt #ユーザ名
      MYSQL_PASSWORD: tt #パスワード
      MYSQL_DATABASE: Reservation_Site #データベース名
    volumes:
      - db:/var/lib/postgres/data #データ永続化
      - ./DB/.sql/:/docker-entrypoint-initd.d #/init.sql #初期化スクリプト
    ports:
      - "5432:5432" #ホストのポート5432をコンテナのポート5432にマッピング

networks: #ネットワーク
  default:
    name: next.js-test-network

volumes: #ボリューム
  db:
    driver: local #ボリュームドライバ
